### ISSUE TITLE
Various Issues at Shrine of Akatosh

### ISSUE THREAD

**Issue by Shanomatic** [GuitarBarbarianOfThunder/eldersouls#102]
**Describe the bug**
A couple terrain issues around the Shrine of Akatosh location just north of Rorikstead. Also appears to be missing a quest item meant to be here, a book called "Kolb and the Dragon," needed for a miscellaneous quest for a girl in Rorikstead.

**To Reproduce**

1. Go to Shrine of Akatosh 
2. Observe

**Expected behavior**
Terrain should be fixed and the book placed, thank you. 

**Screenshots**
![20200525132424_1](https://user-images.githubusercontent.com/65898197/82833288-97a46e80-9e8b-11ea-8595-91879e27f5cd.jpg)
![20200525132428_1](https://user-images.githubusercontent.com/65898197/82833293-9c692280-9e8b-11ea-9997-c6acbcff3b30.jpg)
![20200525132440_1](https://user-images.githubusercontent.com/65898197/82833301-9ffca980-9e8b-11ea-9924-61b78d6a40be.jpg)

**Modlist version**
1.1.7

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 1.1.12
