### ISSUE TITLE
Darkend Dragons Difficulty

### ISSUE THREAD

**Issue by lexcia98** [GuitarBarbarianOfThunder/eldersouls#106]
**Describe the bug**
Dragon bosses in Darkend are by default made stronger then other things in the mod in order to provide difficult and deadly fights. Changes from mods such as Ultimate Dragons take them from doable bosses to content many times harder then anything else in the mod where they will one shot you and it will take multiple times as long as intended to whittle them down. 

**To Reproduce**
Go to Darkend mod area. Progress till dragon boss. 

**Expected behavior**
You will get your shit rocked by the dragon even if able to get through the rest of the mod before that easily. With god mode turned on battling the dragon would still take longer then any other encounter in the mod.

**Comment by jdsmith2816** [comment]
Fixed in 1.1.2  Thanks to alice for the patch.
