### ISSUE TITLE
DISARM SHOUT EXISTS

### ISSUE THREAD

**Issue by lexcia98** [GuitarBarbarianOfThunder/eldersouls#107]
"ok ok ok after watching dwarfdude get demolisehd by disarm shout and hearing zenillion's cries of despair i will commit to nuking draugr disarm next update
jus go bug report it
this si not me saying it was supposed to have been done pre-release
not at all"

https://cdn.discordapp.com/attachments/704708621732151547/715049964715376670/unknown.png

**Comment by jdsmith2816** [comment]
Fixed in 1.1.12
