### ISSUE TITLE
Staff of Shalidor 'Move into Staff' option causing CTD

### ISSUE THREAD

**Issue by SWIFT31S** [GuitarBarbarianOfThunder/eldersouls#110]
**Describe the bug**
Staff of Shalidor's 'Move into the Staff' option that appears on equip crashes the game if clicked. 

**To Reproduce**

1. Equip Staff of Shalidor
2. Click 'Move into the Staff'
3. Game CTD's

**Expected behavior**
Arrive in Staff of Shalidor Playerhome

**Modlist version**
1.17

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Unable to reproduce in v1.1.12
