### ISSUE TITLE
Whiterun floating walls

### ISSUE THREAD

**Issue by vundere** [GuitarBarbarianOfThunder/eldersouls#111]
**Describe the bug**
Floating wall planes and rock outside Whiterun walls.

**To Reproduce**
Go outside Whiterun, walk along the wall until you reach the back of the Skyforge area.

**Expected behavior**
Not seeing floating bits of scenery.

**Screenshots**
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 05 28 - 18 28 14 27](https://user-images.githubusercontent.com/25097150/83168180-5d4c0300-a111-11ea-8aba-95893e13e608.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 05 28 - 18 28 18 16](https://user-images.githubusercontent.com/25097150/83168185-5fae5d00-a111-11ea-832d-f7d17cf0cfd0.png)

**Modlist version**
v1.1.8

**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
Unable to reproduce in 1.1.12; feel free to re-open if you still experience this problem.
