### ISSUE TITLE
Floating door outside Whiterun

### ISSUE THREAD

**Issue by vundere** [GuitarBarbarianOfThunder/eldersouls#112]
**Describe the bug**
A lone door hanging out in the air outside Whiterun.

**To Reproduce**

1. Head past the Washrine west of Whiterun.
2. Look up to the sky, still point west.

**Expected behavior**
Not seeing floating doors.

**Screenshots**
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 05 28 - 19 19 47 07](https://user-images.githubusercontent.com/25097150/83173238-034f3b80-a119-11ea-8894-a898b8055b5e.png)

**Modlist version**
v1.1.8
**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
Fixed in 1.1.12
