### ISSUE TITLE
CTD after entering in interior cell

### ISSUE THREAD

**Issue by Pepin90** [GuitarBarbarianOfThunder/eldersouls#113]
**Describe the bug**
When I tried to enter in Helgen Keep from the cave entrance my game crashes immediately, after a two second black screen. No loading screens appeared before the crash. 
I came from a fast travel in Riverwood and a little walk toward Helgen and a goblins fight. I have played about 30 minutes in today session. 

**To Reproduce**

1. Go to Helgen Keep Cave entrance. 
2. Enter. 

**Expected behavior**
CTD. 

**Modlist version**
Elder Souls 

**Did you add any additional mods?**
CGO with patch from elder souls channel. 
Animations. 
Dynamic animation replacer. 
3pco.
No radial blur. 
Floating damage. 
Sse fixes without the related plugin preloader (settings that I saw here from gamerpoets
poets https://youtu.be/gXklRYVN7mE). 
Reshade Commodore's. 
[Crash_2020_5_29_23-26-29.txt](https://github.com/jdsmith2816/eldersouls/files/4704553/Crash_2020_5_29_23-26-29.txt)

**Comment by jdsmith2816** [comment]
Cannot reproduce on 1.1.12;  Feel free to re-open if you can repeat the problem.
