### ISSUE TITLE
Staff of Magnus Third Person Bug

### ISSUE THREAD

**Issue by SWIFT31S** [GuitarBarbarianOfThunder/eldersouls#115]
**Describe the bug**
The Eye of Magnus appears around the player in third person with the Staff of Magnus equipped.

**To Reproduce**
1. Equip and draw the Staff of Magnus
2. Switch to third-person view
3. Player is now engulfed inside the Eye of Magnus....

**Expected behavior**
Standard third person view

**Screenshots**
![20200527221500_1](https://user-images.githubusercontent.com/65710674/83309388-06bdf200-a201-11ea-8c12-7ac9ea4b0e59.jpg)

**Modlist version**
1.1.7
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 1.1.12
