### ISSUE TITLE
Floating Skeever in Fort Dawnguard

### ISSUE THREAD

**Issue by SWIFT31S** [GuitarBarbarianOfThunder/eldersouls#117]
**Describe the bug**
Random floating Skeever model with no collision in Fort Dawnguard. Has been present across 3 separate characters.

**To Reproduce**
1. Enter Fort Dawnguard
2. Turn the first right after entering
3. Floating Skeever at head height visible in corridor

**Expected behavior**
No floating Skeever, shits me up every time

**Screenshots**
![20200526001159_1](https://user-images.githubusercontent.com/65710674/83309847-3e796980-a202-11ea-84e0-f12232bb4447.jpg)

**Modlist version**
1.1.7

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 1.1.12
