### ISSUE TITLE
Decorative Scrolls/Soul Gems TANK FPS

### ISSUE THREAD

**Issue by SWIFT31S** [GuitarBarbarianOfThunder/eldersouls#118]
**Describe the bug**
Certain decorative piles of scrolls/soul gems/occasionally other random decorations absolutely tank framerate from 120+ to as low as 15. Scroll piles, or displays featuring scrolls are the worst offenders. 

**To Reproduce**
I'm going to use Thornrock as an example, but this happens in MANY places, and almost every player home, but it is not limited to playerhomes.

1. Go to Thornrock (or any other place with decorative scrolls/any items mentioned above)
2. Move close to scroll cabinet (in the case of Thornrock)
3. Watch framerate go from very high to VERY low

Other examples: 
-Ingot Storage in Severin Manor
-Soul Gem Storage in Severin Manor
-Farengar's Orb on the table in Dragonsreach

**Expected behavior**
Stable FPS.

**Screenshots**
![20200530003321_1](https://user-images.githubusercontent.com/65710674/83313371-d892df00-a20d-11ea-9547-029c4551ad50.jpg)
![20200530003333_1](https://user-images.githubusercontent.com/65710674/83313373-d9c40c00-a20d-11ea-93d6-dcbb9297b5d0.jpg)
![20200530003501_1](https://user-images.githubusercontent.com/65710674/83313374-d9c40c00-a20d-11ea-92ab-6427acf94c8f.jpg)

**Modlist version**
1.1.7

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Crystal Ball gone in 1.1.12 but the rest... They're staying as they are for the forseeable future.
