### ISSUE TITLE
Crashes when selling items sometimes its a weapon like the Claw, other times its a Common Tunic (Clothing)

### ISSUE THREAD

**Issue by sweeper240** [GuitarBarbarianOfThunder/eldersouls#120]
**Describe the bug**
I've gotten repeated crashes when selling an item, it was happening regularly with Claws but then it just happened with Clothing (and not the Claw) These random crashes are making the game unplayable due to the restrictive save game functionality as well - since you can't save easily prior to an event that would create a crash and then reload.

**To Reproduce**
Sell items to a vendor in the game

2. Do '...'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**
Latest

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 1.1.12
