### ISSUE TITLE
Millwater Retreat and Dark Forests of Skyrim bug

### ISSUE THREAD

**Issue by WngdDragon** [GuitarBarbarianOfThunder/eldersouls#122]
**Describe the bug**
Millwater Retreat has several trees from Dark Forests going through buildings.

**To Reproduce**

1. Go to 'Millwater Retreat'
2. Look around

**Expected behavior**
No tress going through buildings.

**Screenshots**
![enb2020_5_23_09_12_22](https://user-images.githubusercontent.com/65816426/83390595-6cbd9b80-a3f2-11ea-84ef-96dbfa0dbe88.png)

**Modlist version**
1.1.7

**Did you add any additional mods?**
Nothing that is relevant to this bug.

**Comment by jdsmith2816** [comment]
Fixed in 1.1.12
