### ISSUE TITLE
Thematically fitting temple player home in solitude

### ISSUE THREAD

**Issue by avovom** [GuitarBarbarianOfThunder/eldersouls#123]
Hey JD,

just thought I'd suggest an awesome player home mod that fits thematically with the list. It's in solitude and it's called "solitude rectory" nexus link attached here: https://www.nexusmods.com/skyrimspecialedition/mods/23735

I think it's probably plug and play, as long as the list doesn't edit that specific small space, but I'm not sure what exactly the list modifies in that space so submitting it here.

**Comment by jdsmith2816** [comment]
Thanks for the suggestion but I won't be adding any more homes for the forseeable future.
