### ISSUE TITLE
 a chair clipping in a forge , whiterun,  warmaiden's 

### ISSUE THREAD

**Issue by Bisqt** [GuitarBarbarianOfThunder/eldersouls#130]
**Describe the bug**
A chair clipping in a forge, Whiterun,  war maidens!
**BURN IT**

![ScreenShot7](https://user-images.githubusercontent.com/67216879/85217388-35416f80-b35e-11ea-9c7b-0359faba81fb.png)

**Expected behavior**
not that :)

**Modlist version** 
Elder souls ???

**Did you add any additional mods?**
No!

**Comment by jdsmith2816** [comment]
Fixed in 1.1.12
