### ISSUE TITLE
UI Perk screen text overlap

### ISSUE THREAD

**Issue by ThrasherGX** [GuitarBarbarianOfThunder/eldersouls#36]
**Describe the bug**
The Magicka bar's text on the perk screen overlaps with itself.

**To Reproduce**

1. Equip an item that increases your magicka by at least 10.
2. Open the perk screen.
3. The first digit(s) of your total Magicka will be overlapped with the word Magicka, below the blue bar for Magicka.

Note: It is very likely that this same issue will occur with the Health and Stamina bars as well.

**Expected behavior**
The Magicka text element should be spaced properly with the numeric values, even when there is a bonus amount added.

**Screenshots**
https://imgur.com/a/K1yjxnX

**Modlist version**
1.0.2

**Did you add any additional mods?**
Simple Lock-On

**Comment by jdsmith2816** [comment]
Fixed ages ago
