### ISSUE TITLE
Massively Overleveled Dragon

### ISSUE THREAD

**Issue by ThrasherGX** [GuitarBarbarianOfThunder/eldersouls#45]
**Describe the bug**
Massively over leveled dragon attacking Rorikstead.

**To Reproduce**
Not sure what conditions are used for dragon spawns.  He wasnt there the first time I went to Rorikstead

**Expected behavior**
I should at least have a chance against the dragon.

**Screenshots**
![enb2020_5_8_18_37_42](https://user-images.githubusercontent.com/38668000/81457399-82290800-915b-11ea-86fc-7e7f3d81e631.png)

**Modlist version**
1.0.3
**Did you add any additional mods?**
Simple Lock-On

**Comment by jdsmith2816** [comment]
Fixed in 1.1.12
