### ISSUE TITLE
Elder souls Missing Textures

### ISSUE THREAD

**Issue by FullmetalRoxas** [GuitarBarbarianOfThunder/eldersouls#91]
**Describe the bug**
Missing textures, purple blank spot instead.

**To Reproduce**
Textures seem to be unconnected, and far between. The first i found was at the house in dawnstar, near the river and Black door.
Second was on the top of the poles of the archery targets, this time in the Helgen Intro dungeon

**Expected behavior**
Textures not to be purple? I dont wanna miss anything, but yall know how texture errors go

**Modlist version**
most recent as of 11:04pst on may 20th 2020. version 1.1.6

**Did you add any additional mods?**
not yet :)

**Comment by jdsmith2816** [comment]
Please provide screenshots with the console open and the items selected.

**Comment by jdsmith2816** [comment]
Unable to reproduce and no screenshot sprovided.
