### ISSUE TITLE
Bound Bow FX

### ISSUE THREAD

**Issue by WngdDragon** [GuitarBarbarianOfThunder/eldersouls#94]
**Describe the bug**
Bound Bow FX stops working after a few seconds. To fix, hide bounbow.nif in Insane Armory.

**To Reproduce**

1. Use Bound Bow spell
2. Observe

**Expected behavior**
FX shouldn't stop working.

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**
1.1.7.
**Did you add any additional mods?**
Some NPC replacers and few spells, nothing that is connected to this issue.

**Comment by jdsmith2816** [comment]
Fixed in 1.1.12
