### ISSUE TITLE
High level dragon spawn over Ustengrav

### ISSUE THREAD

**Issue by rshackleton** [GuitarBarbarianOfThunder/eldersouls#95]
**Describe the bug**
A high-level dragon spawn (level 70) over Ustengrav, an early main quest location.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go near Ustengrav

**Expected behaviour**
Such a high-level dragon shouldn't prevent access to an early main story quest location.

**Screenshots**
![image](https://user-images.githubusercontent.com/13448395/82758523-f8c23880-9dde-11ea-949e-31b869abd2cc.png)

**Modlist version**
1.1.7

**Did you add any additional mods?**
Campfire and CGO

**Comment by jdsmith2816** [comment]
I've decided to go ahead and pull Dovahkriid.  They're just causing too many small problems to stick around.

Fixed in 1.12.1
