### ISSUE TITLE
CTD selling to Belethor in Whiterun

### ISSUE THREAD

**Issue by pgdeaner** [GuitarBarbarianOfThunder/eldersouls#96]
[Crash_2020_5_24_20-8-20.txt](https://github.com/jdsmith2816/eldersouls/files/4674917/Crash_2020_5_24_20-8-20.txt)
**Describe the bug**

**To Reproduce**

2. Do '...'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**

**Did you add any additional mods?**
Naucissa's tweaker- Checked in xEdit.

**Comment by jdsmith2816** [comment]
Unable to reproduce on 1.1.12
