### ISSUE TITLE
Pale, White Hands in Fist Person View 

### ISSUE THREAD

**Issue by Shanomatic** [GuitarBarbarianOfThunder/eldersouls#97]
**Describe the bug**
All races have pale, white hands when in first person view. I believe this is caused by a missing texture, however I am not completely sure.

**To Reproduce**

1. Create a character of any race.
2. Compare hand color when in first and third person.

**Expected behavior**
Hand color in both third and first person should match.

**Screenshots**
![20200525062831_1](https://user-images.githubusercontent.com/65898197/82806001-f1d50d80-9e52-11ea-9682-c94140c5acc2.jpg)
![20200525062825_1](https://user-images.githubusercontent.com/65898197/82806010-f7caee80-9e52-11ea-82d2-d5bffb2e4f32.jpg)
![20200525062707_1](https://user-images.githubusercontent.com/65898197/82806025-00232980-9e53-11ea-9524-bca3c914f47a.jpg)
![20200525062658_1](https://user-images.githubusercontent.com/65898197/82806033-04e7dd80-9e53-11ea-92e0-6b070742f606.jpg)
![20200525062644_1](https://user-images.githubusercontent.com/65898197/82806039-06b1a100-9e53-11ea-9a54-5d9491a01ba9.jpg)
![20200525062641_1](https://user-images.githubusercontent.com/65898197/82806043-07e2ce00-9e53-11ea-97fe-483fa9105bb1.jpg)
![20200525062628_1](https://user-images.githubusercontent.com/65898197/82806050-09ac9180-9e53-11ea-932d-d1b8abdd4099.jpg)
![20200525062624_1](https://user-images.githubusercontent.com/65898197/82806052-0b765500-9e53-11ea-9bc4-b501fad9928e.jpg)
![20200525062602_1](https://user-images.githubusercontent.com/65898197/82806057-0d401880-9e53-11ea-9f9a-4849ec6ad727.jpg)
![20200525062558_1](https://user-images.githubusercontent.com/65898197/82806063-0f09dc00-9e53-11ea-9aa8-44c15a540db7.jpg)
![20200525062544_1](https://user-images.githubusercontent.com/65898197/82806072-1204cc80-9e53-11ea-9b13-39f0db545dd9.jpg)
![20200525062540_1](https://user-images.githubusercontent.com/65898197/82806075-13ce9000-9e53-11ea-8648-cd1ed456a223.jpg)
![20200525062528_1](https://user-images.githubusercontent.com/65898197/82806079-1630ea00-9e53-11ea-84a3-ccb55a324f51.jpg)
![20200525062519_1](https://user-images.githubusercontent.com/65898197/82806090-1af59e00-9e53-11ea-962c-5d0c13873ba4.jpg)
![20200525062505_1](https://user-images.githubusercontent.com/65898197/82806093-1c26cb00-9e53-11ea-9dc5-18b3e2f9ed6b.jpg)
![20200525062501_1](https://user-images.githubusercontent.com/65898197/82806098-1e892500-9e53-11ea-9072-f5de67ce1b3f.jpg)
![20200525062434_1](https://user-images.githubusercontent.com/65898197/82806106-20eb7f00-9e53-11ea-9663-94e46d69c5b7.jpg)
![20200525062430_1](https://user-images.githubusercontent.com/65898197/82806111-221cac00-9e53-11ea-92b7-76e34839454b.jpg)
![20200525062409_1](https://user-images.githubusercontent.com/65898197/82806113-23e66f80-9e53-11ea-80eb-8655f671c6de.jpg)
![20200525062403_1](https://user-images.githubusercontent.com/65898197/82806116-25b03300-9e53-11ea-9fbf-d6b4b298a775.jpg)

**Modlist version**
1.1.7
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Whoa, that's weird. Thanks for the report;  I'll take a look.

**Comment by jdsmith2816** [comment]
Unable to reproduce in 1.1.12; feel free to reopen if you are still experiencing this problem after updating.
