### ISSUE TITLE
CTD after opening multiple instances of the training window

### ISSUE THREAD

**Issue by BigFudge34** [GuitarBarbarianOfThunder/eldersouls#98]
**Describe the bug**
A clear and concise description of what the bug is. Game crashes to desktop after training skills due to opening multiple instances of the training window by accident.

**To Reproduce**
Steps to reproduce the behavior: If you level a skill until a level up and sleep again to get the level up screen and quit out of it and immediately sleep again it opens a second instance of the skill up screen on top of the one opened after closing the level up menu in which leveling a skill several times it crashes.

2. Do '...'

**Expected behavior**
A clear and concise description of what you expected to happen. Either for the training window to behave normally or not opening an additional window when there's an active one.

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version** 2.0.6.0

**Did you add any additional mods?**

**Comment by jdsmith2816** [comment]
Thanks!  I know how to fix this and will include it in the next release.

**Comment by jdsmith2816** [comment]
Fixed in 1.1.12
